id: A70B27B70
title: Praise of Noble Avalokiteśvara
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:16:39.291980
  last_modified_at: 2022-03-01 02:16:39.291987
